
const express = require('express');
const router = express.Router();
const crypto = require('crypto');

const API_KEY = (process.env.GEMINI_API_KEY || "").trim();
const WEBHOOK_SECRET = process.env.GITHUB_WEBHOOK_SECRET || "";
const GITHUB_TOKEN = process.env.GITHUB_TOKEN || "";

// Verify GitHub webhook signature (uses raw body bytes — NOT JSON.stringify)
function verifySignature(rawBody, sig) {
    if (!WEBHOOK_SECRET) return true; // Skip if no secret configured
    if (!sig) return false;
    const hmac = crypto.createHmac('sha256', WEBHOOK_SECRET);
    const digest = 'sha256=' + hmac.update(rawBody).digest('hex');
    try {
        return crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(digest));
    } catch { return false; }
}

// Ask Gemini to review a commit — with model fallback (same as neuralCall)
async function reviewCommit(commitData) {
    const prompt = `You are Zylron DevOps AI. Review this GitHub commit and identify any bugs or security issues.
    Commit: ${JSON.stringify(commitData)}
    
    Respond in this format:
    STATUS: OK or ISSUE_FOUND
    SUMMARY: One sentence about what changed.
    ISSUE: (if STATUS is ISSUE_FOUND) Describe the bug/security issue briefly.
    FIX: (if STATUS is ISSUE_FOUND) Suggest the exact fix.`;

    // ✅ Multi-model fallback — never returns "unavailable"
    const models = [
        'gemini-2.0-flash',
        'gemini-1.5-flash',
        'gemini-1.5-flash-8b',
        'gemini-1.5-pro',
    ];

    for (const modelId of models) {
        try {
            const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${modelId}:generateContent?key=${API_KEY}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ contents: [{ role: 'user', parts: [{ text: prompt }] }] })
            });
            if (!res.ok) {
                console.warn(`🔄 DevOps: ${modelId} failed (${res.status}), trying next...`);
                continue;
            }
            const data = await res.json();
            const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
            if (text) {
                console.log(`✅ DevOps Review by ${modelId}`);
                return text;
            }
        } catch (e) {
            console.warn(`🔄 DevOps: ${modelId} error: ${e.message}`);
        }
    }
    return "⚠️ All models busy — review skipped.";
}

// Raise a GitHub PR with fix
async function raisePR(repoFullName, branchName, filename, fixContent, issueDescription) {
    if (!GITHUB_TOKEN) return "❌ No GITHUB_TOKEN set. Cannot raise PR automatically.";
    
    const headers = {
        'Authorization': `token ${GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json'
    };

    try {
        // Get main branch SHA
        const branchRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/ref/heads/main`, { headers });
        const branchData = await branchRes.json();
        const sha = branchData.object?.sha;
        if (!sha) return "❌ Could not get main branch SHA.";

        // Create new branch
        await fetch(`https://api.github.com/repos/${repoFullName}/git/refs`, {
            method: 'POST', headers,
            body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha })
        });

        // Get file SHA to update it
        const fileRes = await fetch(`https://api.github.com/repos/${repoFullName}/contents/${filename}`, { headers });
        const fileData = await fileRes.json();

        // Update file on new branch
        await fetch(`https://api.github.com/repos/${repoFullName}/contents/${filename}`, {
            method: 'PUT', headers,
            body: JSON.stringify({
                message: `🤖 Zylron DevOps: Auto-fix for ${filename}`,
                content: Buffer.from(fixContent).toString('base64'),
                sha: fileData.sha,
                branch: branchName
            })
        });

        // Raise PR
        const prRes = await fetch(`https://api.github.com/repos/${repoFullName}/pulls`, {
            method: 'POST', headers,
            body: JSON.stringify({
                title: `🤖 Zylron Auto-Fix: ${issueDescription.substring(0, 60)}`,
                head: branchName,
                base: 'main',
                body: `## Zylron DevOps AI found an issue:\n\n${issueDescription}\n\nThis PR was automatically generated by Zylron 3.0 CI/CD Agent.`
            })
        });
        const pr = await prRes.json();
        return `✅ PR raised: ${pr.html_url}`;
    } catch (err) {
        return `❌ PR creation failed: ${err.message}`;
    }
}

// 🧪 TEST ENDPOINT - verify route is alive
router.get('/github-webhook', (req, res) => {
    res.json({ status: '✅ Zylron DevOps Webhook is ALIVE', endpoint: 'POST /api/devops/github-webhook' });
});

// 🔥 THE WEBHOOK ENDPOINT
router.post('/github-webhook', async (req, res) => {
    // Acknowledge immediately (GitHub expects fast response)
    res.status(200).json({ received: true, status: 'Zylron DevOps processing...' });

    const event = req.headers['x-github-event'];
    console.log(`🤖 Zylron DevOps: Received GitHub event: ${event}`);
    if (event !== 'push') return;

    const { repository, commits, pusher } = req.body;
    if (!commits || commits.length === 0) return;

    console.log(`🤖 Zylron DevOps: New push to ${repository?.full_name} by ${pusher?.name}`);

    // Review each commit
    for (const commit of commits.slice(0, 3)) { // Max 3 commits per push
        const review = await reviewCommit({
            id: commit.id,
            message: commit.message,
            modified: commit.modified,
            added: commit.added,
            author: commit.author
        });

        console.log(`🔍 Commit Review (${commit.id.substring(0,7)}):`, review.substring(0, 200));

        if (review.includes('ISSUE_FOUND')) {
            console.log('🚨 Issue found! Attempting auto-fix PR...');
            const branchName = `zylron-fix-${Date.now()}`;
            const prResult = await raisePR(
                repository.full_name,
                branchName,
                commit.modified?.[0] || 'README.md',
                `// Zylron DevOps: Auto-fix applied\n// Issue: ${review}`,
                review
            );
            console.log('🤖 PR Result:', prResult);
        }
    }
});

module.exports = router;
